project:
  type: website
  output-dir: docs

website:
  title: "Thomas' Cool Little Website"
  site-path: "/warmup-thomas-spurlock/"
  favicon: images/ea1.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/article_01.qmd
        text: Looping a Triangle
      - href: articles/article_02.qmd
        text: Recursion
      - href: posts (Topic 1)/index.qmd
        text: Church
      - href: posts (Topic 2)/index.qmd
        text: Computer Science

  sidebar:
    - id: articles
      title: "Articles"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/article_01.qmd
        text: Looping a Triangle
      - href: articles/article_02.qmd
        text: Recursion
      - href: posts (Topic 1)/index.qmd
        text: Church Blog
      - href: posts (Topic 2)/index.qmd
        text: Computer Science Blog
      - href: customization.qmd
        text: Customization

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



