project:
  type: website
  output-dir: docs

website:
  title: "Thomas' COOLER Website"
  site-path: "/warmup-thomas-spurlock/"
  favicon: images/ea1.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/main.qmd
        text: Articles
      - href: posts (Topic 1)/index.qmd
        text: Church
      - href: posts (Topic 2)/index.qmd
        text: Computer Science

  sidebar:
    - id: articles
      logo: /images/jerusalem_cross2.png
      title: "Articles"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/main.qmd
        text: Articles
      - href: posts (Topic 1)/index.qmd
        text: Church Blog
      - href: posts (Topic 2)/index.qmd
        text: Computer Science Blog
      - href: movies.qmd
        text: Cool Movie Trailers!

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



