project:
  type: website
  output-dir: docs

website:
  title: "warmup-thomas-spurlock"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Gaming

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



