project:
  type: website
  output-dir: docs

website:
  title: "Thomas' Cool Little Website"
  site-path: "/warmup-thomas-spurlock/"
  favicon: images/ea1.png
  body-header: 
    This website brought to you by me, Thomas 
  margin-header: |
    ![Logo image](images/Roland_horn.jpg.png)
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/article_01.qmd
        text: Looping a Triangle
      - href: articles/article_02.qmd
        text: Recursion

  sidebar:
    - id: articles
      title: "Articles"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/article_01.qmd
        text: Looping a Triangle
      - href: articles/article_02.qmd
        text: Recursion

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



