project:
  type: website
  output-dir: docs

website:
  title: "Thomas' Cool Little Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/article_01.qmd
        text: Looping a Triangle
      - href: articles/article_02.qmd
        text: Recursion
      - href: 404.qmd
        text: Error page (it's a bit scary)

  sidebar:
    - id: articles
      title: "Articles"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/article_01.qmd
        text: Looping a Triangle
      - href: articles/article_02.qmd
        text: Recursion
      - href: 404.qmd
        text: Error page (it's a bit scary)

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



